services:
    database:
        image: postgres:16.4
        container_name: me-journal-database
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: me-journal
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: root
        volumes:
            - me-journal-db-data:/var/lib/postgresql/data
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    me-journal-db-data:
        external: true
